library(ggdendro)
library(ggplot2)
library(ggvis)
library(reshape2)
library(grid)

## colours, generated by
## library(RColorBrewer)
## rev(brewer.pal(11,name="RdYlBu"))
my.colours <- c("#313695", "#4575B4", "#74ADD1", "#ABD9E9", "#E0F3F8", "#FFFFBF",
                "#FEE090", "#FDAE61", "#F46D43", "#D73027", "#A50026")


#position_colors = data.frame(position=c("ra", "arco", "hvc", "ncl", "lman", "nido", "x", "stri", "meso", "ov"),
#                             color=c("#7f0000", "#ef6548",  "#662506", "#cc4c02", "#08306b", "#4292c6", "#49006a", "#ae017e", "#004529", "#41ab5d"))
position_colors = c("#e31a1c", "#ef6548",  "#662506", "#cc4c02", "#08306b", "#4292c6", "#49006a", "#ae017e", "#004529", "#41ab5d")
names(position_colors) = c("ra", "arco", "hvc", "ncl", "lman", "nido", "x", "stri", "meso", "ov")


position_colors = c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928')
names(position_colors) = c("nido", "lman", "stri", "x", "arco", "ra", "ncl", "hvc", "dummy", "ov", "dummy", "meso")

position_upper_colors = c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928')
names(position_upper_colors) = c("NIDO", "LMAN", "STRI", "X", "ARCO", "RA", "NCL", "HVC", "DUMMY", "OV", "dummy", "MESO")


deaf_colors = c("darkred", "darkblue")
names(deaf_colors) = c("deaf", "intact")

duration.of.experiment_colors = c("#1f78b4", "#33a02c", '#e31a1c')
names(duration.of.experiment_colors) = c("4", "9", "14")

mydplot <- function(ddata, row=!col, col=!row, labels=col) {
  ## plot a dendrogram
  yrange <- range(ddata$segments$y)
  yd <- yrange[2] - yrange[1]
  nc <- max(nchar(as.character(ddata$labels$label)))
  tangle <- if(row) { 0 } else { 90 }
  tshow <- col
  p <- ggplot() +
    geom_segment(data=segment(ddata), aes(x=x, y=y, xend=xend, yend=yend)) +
    labs(x = NULL, y = NULL) + theme_dendro()
  if(row) {
    p <- p +
      scale_x_continuous(expand=c(0.5/length(ddata$labels$x),0)) +
      coord_flip()
  } else {
    p <- p +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
  }
  return(p)
}

g_legend<-function(a.gplot){
  ## from
  ## http://stackoverflow.com/questions/11883844/inserting-a-table-under-the-legend-in-a-ggplot2-histogram
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

##' Display a ggheatmap
##'
##' this function sets up some viewports, and tries to plot the dendrograms to line up with the heatmap
##' @param L a list with 3 named plots: col, row, centre, generated by ggheatmap
##' @param col.width,row.width number between 0 and 1, fraction of the device devoted to the column or row-wise dendrogram. If 0, don't print the dendrogram
##' @return no return value, side effect of displaying plot in current device
##' @export
##' @author Chris Wallace
ggheatmap.show <- function(L, col.width=0.2, row.width=0.2) {
  grid.newpage()
  top.layout <- grid.layout(nrow = 2, ncol = 2,
                            widths = unit(c(1-row.width,row.width), "null"),
                            heights = unit(c(col.width,1-row.width), "null"))
  pushViewport(viewport(layout=top.layout))
  if(col.width>0)
    print(L$col, vp=viewport(layout.pos.col=1, layout.pos.row=1))
  if("upper" %in% names(L)) {
    if (!is.null(L$upper)) {
      print(L$upper + theme(axis.line=element_blank(),
                            axis.text.x=element_blank(),axis.text.y=element_blank(),
                            axis.ticks=element_blank(),
                            axis.title.x=element_blank(),axis.title.y=element_blank(),
                            legend.position="none",
                            panel.background=element_blank(),
                            panel.border=element_blank(),panel.grid.major=element_blank(),
                            panel.grid.minor=element_blank(),plot.background=element_blank()), 
            vp=viewport(layout.pos.col=1, layout.pos.row=1))
    }
  }
 
  if("label" %in% names(L)) {
    if(row.width>0)
      print(L$row, vp=viewport(layout.pos.col=2, layout.pos.row=2))
  }
  if(row.width>0)
    print(L$row, vp=viewport(layout.pos.col=2, layout.pos.row=2))
  ## print centre without legend
  print(L$centre +
          theme(axis.line=element_blank(),
                axis.text.x=element_blank(),axis.text.y=element_blank(),
                axis.ticks=element_blank(),
                axis.title.x=element_blank(),axis.title.y=element_blank(),
                legend.position="none",
                panel.background=element_blank(),
                panel.border=element_blank(),panel.grid.major=element_blank(),
                panel.grid.minor=element_blank(),plot.background=element_blank()),
        vp=viewport(layout.pos.col=1, layout.pos.row=2))
  ## add legend
  legend <- g_legend(L$centre)
  pushViewport(viewport(layout.pos.col=2, layout.pos.row=1))
  grid.draw(legend)
  upViewport(0)
}

##' Display a ggheatmap
##'
##' this function sets up some viewports, and tries to plot the dendrograms to line up with the heatmap
##' @param L a list with 3 named plots: col, row, centre, generated by ggheatmap
##' @param col.width,row.width number between 0 and 1, fraction of the device devoted to the column or row-wise dendrogram. If 0, don't print the dendrogram
##' @return no return value, side effect of displaying plot in current device
##' @export
ggheatmap.2.show <- function(L, col.width=0.2, row.width=0.2) {
  grid.newpage()
  top.layout <- grid.layout(nrow = 2, ncol = 3,
                            widths = unit(c(row.width, 1-2*row.width,row.width), "null"),
                            heights = unit(c(col.width,1-row.width), "null"))
  pushViewport(viewport(layout=top.layout))
  
  blank_theme = theme(axis.line=element_blank(),
                      axis.text.x=element_blank(),axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
                      axis.title.x=element_blank(),axis.title.y=element_blank(),
                      legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),plot.background=element_blank())
  if(col.width>0)
    print(L$col, vp=viewport(layout.pos.col=1, layout.pos.row=1))
  if("upper" %in% names(L)) {
    if (!is.null(L$upper)) {
      print(L$upper + theme(axis.line=element_blank(),
                            axis.text.x=element_blank(),axis.text.y=element_blank(),
                            axis.ticks=element_blank(),
                            axis.title.x=element_blank(),axis.title.y=element_blank(),
                            legend.position="none",
                            panel.background=element_blank(),
                            panel.border=element_blank(),panel.grid.major=element_blank(),
                            panel.grid.minor=element_blank(),plot.background=element_blank()), 
            vp=viewport(layout.pos.col=2, layout.pos.row=1))
    }
  }
  
  if("label" %in% names(L)) {
    print(L$label + blank_theme, vp=viewport(layout.pos.col=1, layout.pos.row=2))
  }
  
  if ("row" %in% names(L)) {
    if(row.width>0)
      print(L$row, vp=viewport(layout.pos.col=3, layout.pos.row=2))
  }
  
  ## print centre without legend
  print(L$centre +
          theme(axis.line=element_blank(),
                axis.text.x=element_blank(),axis.text.y=element_blank(),
                axis.ticks=element_blank(),
                axis.title.x=element_blank(),axis.title.y=element_blank(),
                legend.position="none",
                panel.background=element_blank(),
                panel.border=element_blank(),panel.grid.major=element_blank(),
                panel.grid.minor=element_blank(),plot.background=element_blank()),
        vp=viewport(layout.pos.col=2, layout.pos.row=2))
  
  ## add legend
  legend <- g_legend(L$centre)
  pushViewport(viewport(layout.pos.col=3, layout.pos.row=1))
  grid.draw(legend)
  upViewport(0)
}


##' generate a heatmap + dendrograms, ggplot2 style
##'
##' @param x data matrix
##' @param hm.colours vector of colours (optional)
##' @return invisibly returns a list of ggplot2 objects. Display them with ggheatmap.show()
##' @author Chris Wallace
##' @export
##' @examples
##' ## test run
##' ## simulate data
##' library(mvtnorm)
##' sigma=matrix(0,10,10)
##' sigma[1:4,1:4] <- 0.6
##' sigma[6:10,6:10] <- 0.8
##' diag(sigma) <- 1
##' X <- rmvnorm(n=100,mean=rep(0,10),sigma=sigma)
##'  
##' ## make plot
##' p <- ggheatmap(X)
##'  
##' ## display plot
##' ggheatmap.show(p)
ggheatmap <- function(x,
                      row.hc=NULL,
                      col.hc=NULL,
                      hm.colours=my.colours,
                      order.cols=FALSE,
                      method="correlation",
                      color_range=c(0,1),
                      info=NULL,
                      to_color=NULL,
                      colors=NULL,
                      to_label=NULL) {
  if(is.null(colnames(x)))
    colnames(x) <- sprintf("col%s",1:ncol(x))
  if(is.null(rownames(x)))
    rownames(x) <- sprintf("row%s",1:nrow(x))
  
  ## plot a heatmap
  ## x is an expression matrix
  if (is.null(row.hc)) {
    row.hc <- hclust(dist(x, method=method), "ward")
  } 
  
  #if (is.null(col.hc)) {
  #  col.hc <- hclust(dist(x, method=method), "ward")
  #} 
  
  row.dendro <- dendro_data(as.dendrogram(row.hc),type="rectangle")
  if (order.cols & is.null(col.hc)) {
    col.hc <- hclust(dist(t(x)), "ward")
  }
  if (order.cols | !is.null(col.hc)) {
    col.dendro <- dendro_data(as.dendrogram(col.hc),type="rectangle")
  }
  
  ## dendro plots
  
  ## COL DENDROGRAM ----------------------------------------------------------------------------------------------------
  if (order.cols | !is.null(col.hc)) {
    col.plot <- mydplot(col.dendro, col=TRUE, labels=TRUE) +
    scale_x_continuous(breaks = 1:ncol(x),labels=col.hc$labels[col.hc$order]) +
    theme(plot.margin = unit(c(0,0,0,0), "lines"))
  }
  
  ## ROW DENDROGRAM ----------------------------------------------------------------------------------------------------
  row.plot <- mydplot(row.dendro, row=TRUE, labels=FALSE) +
    theme(plot.margin = unit(rep(0, 4), "lines"))
  
  ## order of the dendros
  if (order.cols | !is.null(col.hc)) {
    col.ord <- match(col.dendro$labels$label, colnames(x))
  }
  row.ord <- match(row.dendro$labels$label, rownames(x))
  if (order.cols | !is.null(col.hc)) {
    xx <- x[row.ord,col.ord]
  } else {
    xx = x[row.ord,]
  }
  dimnames(xx) <- NULL
  xx <- melt(xx)
  colnames(xx) = c("Var1", "Var2", "value")
  
  
  ## CENTER PLOT -------------------------------------------------------------------------------------------------------
  centre.plot <- ggplot(xx, aes(Var2,Var1)) + geom_raster(aes(fill=value)) +
    labs(x = NULL, y = NULL) +
    scale_x_continuous(expand=c(0,0)) +
    scale_y_continuous(expand=c(0,0),breaks = NULL) +
    theme(plot.margin = unit(rep(0, 4), "lines"))
  
  if (hm.colours == "viridis") {
    centre.plot = centre.plot +  scale_fill_viridis(limits=c(color_range[1], color_range[2]))
  } else {
    if (length(color_range)==2) {
      centre.plot = centre.plot +  scale_fill_gradientn(colours = hm.colours, limits=c(color_range[1], color_range[2])) 
    } else if (length(color_range)==4) {
      centre.plot = centre.plot +  scale_fill_gradientn(colours = hm.colours, breaks=c(color_range[1],
                                                                                       seq(color_range[2], color_range[3], .1),
                                                                                       color_range[4])) 
    }
    
  }
  
  ## UPPER PLOT
  upper_plot = NULL
  if (!is.null(info)) {
    ## sample plots
    rect_width = .05
    offset = rect_width# * scale_factor
    yval = 0
    labels = data.frame(x=1:nrow(info), y=yval, info)
    labels$y1 = labels$y - offset
    labels$x_end = labels$x + 1
    labels$y1_end = labels$y1 + rect_width
    if (length(to_color) > 1) {
      for (i in 2:length(to_color)) {
        labels[,paste0("y", i)] = labels[,paste0("y", i-1)] + offset
        labels[,paste0("y", i, "_end")] = labels[,paste0("y", i)] + rect_width
      }
    }
    
    if (!is.null(to_color)) {
      upper_plot = ggplot(labels)
      for (i in 1:length(to_color)) {
        upper_plot = upper_plot + geom_rect(aes_string(xmin = "x",
                                                       xmax = "x_end",
                                                       ymin = paste0("y", i),
                                                       ymax = paste0("y",i, "_end"),
                                                       fill=to_color[i]))
        #scale_y_continuous(expand=c(0,0),breaks = NULL) 
        
      }
      upper_plot = upper_plot + theme(plot.margin = unit(rep(0, 4), "lines"),
                                      legend.position="none") +
        labs(x = NULL, y = NULL) +
        scale_x_continuous(expand=c(0,0)) 
      upper_plot = upper_plot + scale_fill_manual(values=colors)
    } 
  } else {
    upper_plot = NULL
  }
  
  ## LABELS -------------------------------------------------------------------------
  label.plot = NULL
  if (!is.null(to_label)) {
    label_df = data.frame(x=row.dendro$labels$y, y=row.dendro$labels$x, label=row.dendro$labels$label)

    label_df$label[!label_df$label %in% to_label] = NA
    label.plot = ggplot(label_df) + geom_text(aes(x=x, y=y, label=label), size=4) 
    label.plot = label.plot #+ geom_segment(aes(x=x, y=y, xend=(x+1), yend=y))
    label.plot = label.plot + labs(x = NULL, y = NULL)# + scale_x_continuous(expand=c(0,0)) 
  }

  if (order.cols) {
    ret <- list(col=col.plot,row=row.plot,centre=centre.plot, upper=upper_plot)
  } else {
    if (is.null(to_label)) {
    ret <- list(row=row.plot,centre=centre.plot, upper=upper_plot)
    } else {
      ret = list(row=row.plot, centre=centre.plot, upper=upper_plot, label=label.plot)
    }
  }
  invisible(ret)
}


#' Title
#'
#' @param d, output from dendro_data
#' @param to_color, variable to color labels by
#'
#' @return ggplot objeect
#' @export
#'
#' @examples
gg_plot_tree = function(d, to_color, colors, scale_factor = 1, include_labels=FALSE) {
  segs = segment(d)
  ymax = max(segs[,2]); ymin = min(segs[,2])
  segs[,2] = (segs[,2] - ymin) / (ymax - ymin)
  segs[,4] = (segs[,4] - ymin) / (ymax - ymin)
  segs[,2] = segs[,2] * scale_factor
  segs[,4] = segs[,4] * scale_factor
  sig_width = segs[2,1] - segs[1,1]
  labels = d$labels
  rect_width = .05
  offset = .1# * scale_factor
  labels$y1 = labels$y - offset
  labels$x_end = labels$x + 1
  labels$y1_end = labels$y1 - rect_width
  if (length(to_color) > 1) {
    for (i in 2:length(to_color)) {
      labels[,paste0("y", i)] = labels[,paste0("y", i-1)] - offset
      labels[,paste0("y", i, "_end")] = labels[,paste0("y", i)] - rect_width
    }
  }
  
  if (include_labels) {
    labels[,"y_text"] = labels[,paste0("y", length(to_color))] - offset
  }


  dd = ggplot(segs) + 
    geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) + 
    #scale_y_continuous(expand=c(2,0))
    coord_flip() + 
    scale_y_reverse(expand = c(2, 0))

  for (i in 1:length(to_color)) {
    dd = dd + geom_rect(data = labels,
                         aes_string(xmin = "x",
                                    xmax = "x_end",
                                    ymin = paste0("y", i),
                                    ymax = paste0("y",i, "_end"),
                                    fill=to_color[i]))
    
    
  }
  dd = dd + scale_fill_manual(values=colors)
  
  if (include_labels) {
    dd = dd + geom_text(data = labels,
                       aes_string(x = "x",
                                  y = "y_text",
                                  label = "id",
                                  hjust = -1,
                                  angle = 0,
                                  vjust = 0), size=1)
  }
  
  dd = dd + theme_dendro() + theme(plot.margin=unit(c(0,0,0,-8), units = "lines"),
                                   legend.position=c(.8, .5))
  dd
}

ggvis_plot_tree = function(d, to_color, scale_factor = 1) {
  segs = segment(d)
  segs[,2] = segs[,2] * scale_factor
  segs[,4] = segs[,4] * scale_factor
  
  labels = d$labels
  offset = .1# * scale_factor
  labels$y1 = labels$y - offset
  if (length(to_color) > 1) {
    for (i in 2:length(to_color)) {
      labels[,paste0("y", i)] = labels[,paste0("y", i-1)] - offset
    }
  }
  
  dd = segs %>% 
    ggvis(x=~x, y=~y, xend=~xend, yend=~yend) %>%
    layer_paths()
    
  # dd = ggplot(segs) + 
  #   geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) + 
  #   coord_flip() + 
  #   scale_y_reverse(expand = c(2, 0))
  # 
  # # c1 = ggplot(d$labels, aes_string(x = "x", 
  # #                                      y = "y",
  # #                                      color=to_color
  # #                                     ###  shape = "c"
  # #                                      #hjust = -1, 
  # #                                      #angle = 0, 
  # #                                      #vjust = 0,
  # #                                       )) + geom_point(shape=15, size=.5)
  # #c1 = c1 + coord_flip() + theme(plot.margin=unit(c(1,1,1,1), units = "lines"))
  # #c1 = c1 + ylim(-.01, .01)
  # # dd = dd + geom_point(data = d$labels,
  # #                    aes_string(x = "x",
  # #                               y = "y",
  # #                               label = "id",
  # #                               color=to_color,
  # #                               hjust = -1,
  # #                               angle = 0,
  # #                               vjust = 0,
  # #                               size=2), size=.5, shape=22)
  # 
  # for (i in 1:length(to_color)) {
  #   dd = dd + geom_point(data = labels,
  #                        aes_string(x = "x",
  #                                   y = paste0("y", i),
  #                                   color=to_color[i]), 
  #                        size=.5, shape=22)
  # }
  # # dd = dd + geom_point(data = d$labels,
  # #                     aes_string(x = "x",
  # #                                y = "y2",
  # #                                label = "id",
  # #                                color=to_color,
  # #                                hjust = -1,
  # #                                angle = 0,
  # #                                vjust = 0,
  # #                                size=2), shape=22, size=.5)
  # dd = dd + theme_dendro() #+ theme(plot.margin=unit(c(1,1,1,1), units = "lines"))
  dd
  #grid.arrange(dd, c1, layout_matrix=rbind(c(1,2), c(1,2)))
}

### TODO added columns to right of tree colored by group

plot_gene_by_position = function(data, genes, value, x_value="position3", color_value=NULL, colors=NULL) {
  #data$position3 = toupper(data$position3)
  d = NULL
  genes_df = data.frame(gene_id=genes)
  d = semi_join(data, genes_df, copy=T)
  if ("tbl" %in% class(data)) {
    d = collect(d, n=Inf)
  } #else {
    #d = d
  #}
  #print(head(d))
  gg = ggplot(d, 
              aes_string(x_value, value))
  if (is.null(color_value)) {
    gg = gg + geom_point(position=position_jitter(width=.2), alpha=I(1/5))
  } else {
    gg = gg + geom_point(aes_string(color=color_value),
                         position=position_jitter(width=.2), 
                         alpha=I(1/5))
    #gg = gg + scale_color_brewer(palette = "Set1")
    gg = gg + scale_color_manual(values=colors)
  }

  gg = gg + facet_grid(gene_id~.)
  gg = gg + labs(x="")
  gg = gg + theme_classic()
  gg = gg + theme(axis.text.x=element_text(angle=45, hjust=1, size=12))
  print(gg)
  return(gg)
}

plot_gene_by_position_grid = function(data, genes, value, color_value=NULL, grid_x=NULL, grid_y=NULL) {
  gg = ggplot(data %>% filter(gene_id %in% genes), 
              aes_string("position3", value))
  if (is.null(color_value)) {
    gg = gg + geom_point(position=position_dodge(width=.2), alpha=I(1/5))
  } else {
    gg = gg + geom_point(aes_string(group=color_value),
                         position=position_dodge(width=.2), 
                         alpha=I(1/5),
                         color=1)
    gg = gg + scale_color_brewer(palette = "Set1")
  }
  
  
  gg = gg + stat_summary(fun.data="mean_cl_boot", 
                         mapping=aes_string(color=color_value),
                         position=position_dodge(width=.2)
  )
  
  if (is.null(grid_x) && !is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(grid_y,"~.", sep="")))
  } else if (!is.null(grid_x) && is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(".~", grid_x, sep="")))
  } else if (!is.null(grid_x) && !is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(grid_y,"~", grid_x, sep="")))
  }
  gg = gg + labs(x="", y = "log2 normalized expression")
  gg = gg + theme_classic()
  gg = gg + theme(axis.text.x=element_text(angle=45, hjust=1))
  print(gg)
  return(gg)
}

plot_gene_by_gene_grid = function(data, genes, value, geom="point", color_value=NULL, sig = NULL, grid_x=NULL, grid_y=NULL) {
  data = data %>% filter(gene_id %in% genes)
  data = data %>% mutate(gene_id = factor(gene_id, levels=levels(genes)))
  dodge_width=.4
  gg = ggplot(data,
              aes_string("gene_id", value))
  if (is.null(color_value)) {
    if (geom=="point") {
      gg = gg + geom_point(position=position_dodge(width=dodge_width), alpha=I(1/10))
    } else if (geom=="violin") {
      gg = gg + geom_violin(position=position_dodge(width=dodge_width))
    } else if (geom=="box") {
      gg = gg + geom_boxplot(position=position_dodge(width=dodge_width), notch = F)
    }

  } else {
    if (geom=="point") {
      gg = gg + geom_point(aes_string(group=color_value),
                         position=position_dodge(width=dodge_width), 
                         alpha=I(1/10))
    } else if (geom=="violin") {
      gg = gg + geom_violin(aes_string(color=color_value),
                            position=position_dodge(width=dodge_width))
    } else if (geom=="box") {
      gg = gg + geom_boxplot(aes_string(color=color_value),
                            position=position_dodge(width=dodge_width), notch=F)
    }
    
    gg = gg + scale_color_brewer(palette = "Set1")
  }
  
  if (geom=="point") {
    gg = gg + stat_summary(fun.data="mean_cl_boot", 
                           mapping=aes_string(color=color_value),
                           position=position_dodge(width=dodge_width))
  }
  if (is.null(grid_x) && !is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(grid_y,"~.", sep="")))
  } else if (!is.null(grid_x) && is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(".~", grid_x, sep="")))
  } else if (!is.null(grid_x) && !is.null(grid_y)) {
    gg = gg + facet_grid(as.formula(paste(grid_y,"~", grid_x, sep="")))
  }
  
  if (!is.null(sig)) {
    sig_genes = genes[sig]
    sig_data = data.frame(gene_id=genes, sig_label = ifelse(sig, "*", "NS"), y=max(data[,value]))
    gg = gg + geom_text(data=sig_data, aes(x=gene_id, y=y, label=sig_label))
  }
  
  gg = gg + labs(x="", y = "log2 normalized expression")
  gg = gg + theme_classic()
  gg = gg + theme(axis.text.x=element_text(angle=45, hjust=1))
  print(gg)
  return(gg)
}








